name: 'knative-env-action'
description: 'Injects a given .env file into your knative declaration'
author: 'inooid'

# Define your inputs here.
inputs:
  input:
    description: 'The input knative yaml file'
    required: true

  env_file:
    description: 'The .env file'
    required: true

  output:
    description: 'The output file path'

  container_name:
    description: 'The container name that will receive the env var'

# Define your outputs here.
outputs:
  output:
    description: 'The newly generated knative yaml file'

runs:
  using: node20
  main: dist/index.js
