name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-service-action:
    name: GitHub Actions Test with kind Service
    runs-on: ubuntu-latest

    env:
      MANIFEST_LOCATION: us-east1
      MANIFEST_SERVICE_ACCOUNT: my-fake-service-account@example.org
      MANIFEST_IMAGE: node:lts
      MANIFEST_INJECTED_VARIABLE: bar

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          input: ./__tests__/__mocks__/service.yaml
          env_file: ./__tests__/__mocks__/test.env

      - name: Test if new manifest exists
        run: |
          if [ ! -f ${{ steps.test-action.outputs.output }} ]; then
            echo "File not found!"
            exit 1
          fi

          cat ${{ steps.test-action.outputs.output }}

  test-job-action:
    name: GitHub Actions Test with kind Job
    runs-on: ubuntu-latest

    env:
      MANIFEST_LOCATION: eu-west4
      MANIFEST_SERVICE_ACCOUNT: my-fake-service-account@example.org
      MANIFEST_IMAGE: node:lts
      MANIFEST_INJECTED_VARIABLE: baz

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          input: ./__tests__/__mocks__/job.yaml
          env_file: ./__tests__/__mocks__/test.env

      - name: Test if new manifest exists
        run: |
          if [ ! -f ${{ steps.test-action.outputs.output }} ]; then
            echo "File not found!"
            exit 1
          fi

          cat ${{ steps.test-action.outputs.output }}
